### ISSUE TITLE
#include "resources.h"

### ISSUE THREAD

**Issue by salasidis** [khoih-prog/Portenta_H7_AsyncWebServer#3] opened 2022-05-10 00:49 UTC
I am likely not doing something right, but I am trying to compile the Async_advancedWebServer.ino example for a Portenta H7, and I get a compile error

C:\Users\RS\AppData\Local\Arduino15\packages\arduino\hardware\mbed_portenta\3.0.1\libraries\WiFi\src\WiFi.cpp:220:10: fatal error: resources.h: No such file or directory
Multiple libraries were found for "WiFiClient.h"
 #include "resources.h"
 Used: C:\Users\RS\AppData\Local\Arduino15\packages\arduino\hardware\mbed_portenta\3.0.1\libraries\WiFi
          ^~~~~~~~~~~~~
 Not used: C:\Users\RS\Documents\Arduino\libraries\WiFiEspAT
compilation terminated.
exit status 1
Error compiling for board Arduino Portenta H7 (M7 core).

Any idea how to fix this?

Thanks

**Comment by khoih-prog** [comment] 2022-05-10 03:35
I've just recompiled with same core v3.0.1 and OK

I think your mbed_portenta core installation is corrupted somehow. You can try remove then reinstall the core.

If still not OK, post the question in Arduino Forum to ask for help.

I'm closing the issue now because this is not a bug of the library.

Good Luck,


![Selection_005](https://user-images.githubusercontent.com/57012152/167537383-1e1cabc0-c528-49db-ab32-4a2c38fcbf0f.png)

**Closed by khoih-prog** 2022-05-10 03:35 UTC

**Comment by salasidis** [comment] 2022-05-10 19:11
I realize you are probably very busy and will not be able to answer or help, but will give it a go anyways.

I can compile the non Async files OK. I am getting the error resources.h not found when compiling any of the Async libraries. The file is there in

C:\Users\RS\AppData\Local\Arduino15\packages\arduino\hardware\mbed_portenta\3.0.1\cores\arduino\mbed\connectivity\drivers\wifi\COMPONENT_WHD\wifi-host-driver\resources\firmware\COMPONENT_4343W

But the compiler seems to not be finding it.

I have previously done a complete uninstall of all Arduino components on my PC, including a registry clean up for a bug where I am getting an error when I compile to M4 core. I get the following error there

c:\users\Mydir\appdata\local\arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\arm-none-eabi\include\c++\7.2.1\system_error:39:10: fatal error: bits/error_constants.h: No such file or directory
#include <bits/error_constants.h

Here too, there are lots of error_constants.h in the file directory – but it is not finding them.

The cleanup had not helped. For this time, I uninstalled the Portenta 3.0.1 board manager, and installed 3.0.0 – same issue. I upgraded to 3.0.1, and still the same issue.

Not sure where to go from here – is it a time out issue or something?

Robert

**Comment by salasidis** [comment] 2022-05-10 20:27
I made some file copies, and now all compile, but not sure if other issues will crop up

For the error_constants.h file, I copied the one present in

C:\Users\RS\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\arm-none-eabi\include\c++\7.2.1\arm-none-eabi\thumb\v8-m.main\fpv5\softfp\bits

To

c:\users\RS\appdata\local\arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\arm-none-eabi\include\c++\7.2.1\system_error:39:10: fatal error: bits/error_constants.h: No such file or directory
#include <bits/error_constants.h

And M4 Core now compiles




For the resources.h file

I copied the one in

C:\UsersRS\AppData\Local\Arduino15\packages\arduino\hardware\mbed_portenta\3.0.1\cores\arduino\mbed\connectivity\drivers\wifi\COMPONENT_WHD\wifi-host-driver\resources\firmware\COMPONENT_4343W

To


C:\Users\RS\AppData\Local\Arduino15\packages\arduino\hardware\mbed_portenta\3.0.1\libraries\WiFi\src



The Async servers now compile, and run

Assuming my changes will not cause any hidden issues, at least I can compile the example code now.




From: rsalasidis
Sent: May 10, 2022 15:11
To: 'khoih-prog/Portenta_H7_AsyncWebServer' ***@***.***>
Subject: RE: [khoih-prog/Portenta_H7_AsyncWebServer] #include "resources.h" (Issue #3)

I realize you are probably very busy and will not be able to answer or help, but will give it a go anyways.

I can compile the non Async files OK. I am getting the error resources.h not found when compiling any of the Async libraries. The file is there in

C:\Users\RS\AppData\Local\Arduino15\packages\arduino\hardware\mbed_portenta\3.0.1\cores\arduino\mbed\connectivity\drivers\wifi\COMPONENT_WHD\wifi-host-driver\resources\firmware\COMPONENT_4343W

But the compiler seems to not be finding it.

I have previously done a complete uninstall of all Arduino components on my PC, including a registry clean up for a bug where I am getting an error when I compile to M4 core. I get the following error there

c:\users\Mydir\appdata\local\arduino15\packages\arduino\tools\arm-none-eabi-gcc\7-2017q4\arm-none-eabi\include\c++\7.2.1\system_error:39:10: fatal error: bits/error_constants.h: No such file or directory
#include <bits/error_constants.h

Here too, there are lots of error_constants.h in the file directory – but it is not finding them.

The cleanup had not helped. For this time, I uninstalled the Portenta 3.0.1 board manager, and installed 3.0.0 – same issue. I upgraded to 3.0.1, and still the same issue.

Not sure where to go from here – is it a time out issue or something?

Robert
